### ISSUE TITLE
Suggest an alternative to the --all flag

### ISSUE THREAD

**Issue by apple-corps** [nerab/manbook#1]
I tried using the all option to create all manpages, but got

 opts.on("--all", "Create a book with all man pages") do |dir|
    ManBook.logger.info "Creating a book with all man pages"
    raise "Not yet implemented"  
  end

As an alternative, I used

manbook $(apropos . | awk '{ print $1 }' | xargs)

**Comment by apple-corps** [comment]
After doing this and creating the toc, and zipping the directory and changing the extension, it created a 40 meg monster. This took my desktop a few minutes to load, and think it would probably crash the kindle.

**Comment by nerab** [comment]
Thanks. Could you submit this as a pull request?
